language: node_js
node_js:
  - "10"
env:
  global:
addons:
  ssh_known_hosts:
    - 106.12.80.76
before_install:
  - env
install:
  - yarn
script:
  - echo 123 > aa.txt
after_success:
  - yarn test:qiniu
notifications:
  email:
    recipients:
      - 445172495@qq.com
    on_success: always
    on_failure: always
