language: java
addons:
  ssh_known_hosts:
    - 106.12.80.76
before_install:
  - env
  - sudo apt-get install -y sshpass
install:
  - echo install
script:
  - echo script
after_success:
  - sshpass -p $DEPLOY_HOST_SSH_PASSWORD ssh $DEPLOY_HOST_SSH_USERNAME@$DEPLOY_HOST "ls; echo 123 >> a.txt;"
  - ssh
  - ssh $DEPLOY_HOST_SSH_USERNAME@$DEPLOY_HOST
notifications:
  email:
    recipients:
      - 445172495@qq.com
    on_success: always
    on_failure: always
